yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    #  Главная страница
    path('', views.index),
    #  Группа
    path('group/<slug:slug>/', views.group_list, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group, on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

        def __str__(self):
            return self.text

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group
MESSAGES = 10  # Количество выводимых новых сообщений
# https://i.postimg.cc/k5hwXXk0/WM-Screenshots-20230323172837.png


def index(request):
    posts = Post.objects.order_by('-pub_date')[:MESSAGES]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:MESSAGES]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/CardOfPost_index.html
<article>
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  </article>
  {% if not forloop.last %}<hr>{% endif %}

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="static/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="static/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="static/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>    
  <header>
    {% include 'includes/header.html' %}
  </header>
  <main>
    <div class="container py-5">
    {% block content %}
      Контент не подвезли :(
    {% endblock content %}
  </main>
    <footer>
      {% include 'includes/footer.html' %}    
    </footer>
  </body>
</html>

yatube/templates/cardOfPost.html
<article>
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
   <p>{{ post.text }}</p>
 </article>
 {% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© 2023 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="index.html">
          <img src="{% static 'img/fav/favicon-32x32.png' %}">
          <span style="color:red">Ya</span>tube</a>
        </a>
      </div>
    </nav>      
  </header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock title %}
{% block content %}
  <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in posts %}
    {% include 'cardOfPost.html' %}
  {% endfor %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
 Главная страница Yatube
{% endblock title %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in posts %}
  {% include 'CardOfPost_index.html' %}
  {% endfor %}
{% endblock content %}